# This is a basic workflow to help you get started with Actions

name: CI TEST

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  mocha-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cd into proj
      run: cd my-app
    - name: install dep
      run: npm install
    - name: console log
      run: pwd && ls -al
    - name: execute
      run: cd my-app && npm test


